my_snring=input('Введите текст:  ')
print(my_snring .upper())
print(my_snring.lower())
print(my_snring.replace(' '  ,'#'))
print(my_snring .replace(' ',''))
print('Количество знаков в строке', my_snring, '17')
print('Первый символ строки',my_snring , ' -П')
print('Последний символ строки',my_snring, ' -г')
